service: monorepo-webhook
provider:
  name: aws
  runtime: python3.7
  stage: serverless
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "codepipeline:StartPipelineExecution"
      Resource: arn:aws:codepipeline:eu-central-1:#{AWS::AccountId}:*

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

functions:
  monorepoWebhook:
    handler: webhook.handler.main
    environment:
      BRANCH_ROUTE: ${file(serverless.conf.yml):branch_routing.route}
      BRANCH_ROUTES: ${file(serverless.conf.yml):branch_routing.routes}
      PROJECT_NESTED: ${file(serverless.conf.yml):project.nested}
      PROJECT_PREFIX_REPO: ${file(serverless.conf.yml):project.prefix_repo_name}
      PROJECT_PREFIX_PARENT: ${file(serverless.conf.yml):project.prefix_parent_folder}
    events:
      - http:
          path: webhook
          method: post
          cors: true