service: monorepo
provider:
  name: aws
  runtime: python3.7
  stage: webhook
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "codepipeline:StartPipelineExecution"
      Resource: arn:aws:codepipeline:eu-central-1:#{AWS::AccountId}:*

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
  serverless-offline:
    port: 4000

functions:
  handler:
    handler: webhook.handler.handle
    environment:
      GITHUB_WEBHOOK_SECRET: supersecretsecret
      BRANCH_ROUTE: ${file(serverless.conf.yml):branchRouting.route}
      BRANCH_ROUTES:  ${file(serverless.conf.js):branchRoutes}
      PROJECT_SERVICE_MODEL: ${file(serverless.conf.yml):project.serviceModel}
      PROJECT_PREFIX_REPO: ${file(serverless.conf.yml):project.prefixRepoName}
      PROJECT_PREFIX_PARENT: ${file(serverless.conf.yml):project.prefixParentFolder}
    events:
      - http:
          path: webhook
          method: post
          cors: true